apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: brpatel9260/nodeapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: '3000'
